version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres      
      POSTGRES_DB: postgres-dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.local
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db

volumes:
  postgres-data:
